[colors]
background = '#0b0e14'
foreground = '#bfbfb6'
selection-background = '#bfbfb6'
selection-foreground = '#091613'
cursor = '#bfbfb6'
black = '#0b0e14'
red = '#f26d78'
green = '#7fd962'
yellow = '#ffb454'
blue = '#59c2ff'
magenta = '#d2a6ff'
cyan = '#95e6cb'
white = '#bfbdb6'
light-black = '#565b66'
light-red = '#f26d78'
light-green = '#7fd962'
light-yellow = '#ffb454'
light-blue = '#59c2ff'
light-magenta = '#d2a6ff'
light-cyan = '#95e6cb'
light-white = '#bfbdb6'
