theme = "ayu_neue"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
auto-save = true
completion-trigger-len = 1
true-color = true
auto-pairs = true
rulers = [100]
idle-timeout = 50
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff", "spacer"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "▏"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.soft-wrap]
enable = true
wrap-indicator = "↪  "

[editor.statusline]
left = ["mode", "spinner", "spacer", "version-control", "workspace-diagnostics"]
center = ["file-name"]
right = [
  "diagnostics",
  "file-encoding",
  "position",
  "total-line-numbers",
  "position-percentage",
  "spacer",
  "file-type",
]

[keys.normal]
"esc" = ["collapse_selection", ":w"]

[keys.select]
"esc" = ["collapse_selection", "normal_mode", ":w"]

[keys.insert]
C-space = "completion"
"esc" = ["normal_mode", ":w"]
